### ISSUE TITLE
unable to process up-down feature.

### ISSUE THREAD

**Issue by catfish132** [jianjieluo/SCD-Net#1]
![image](https://user-images.githubusercontent.com/56590427/229513215-a1fc7d21-b8f0-44cf-8e9e-1ce1d1ac73f1.png)
I run tools/create_feats.py, but it throw out this problem. I turn the mode into read text, but still not work.
Could you please tell me what is wrong?

**Comment by jianjieluo** [comment]
Hi, @catfish132 ,
`tools/create_feats.py` is modified from the [read_tsv.py](https://github.com/peteanderson80/bottom-up-attention/blob/master/tools/read_tsv.py) in the original BUTD repo. I suggest you to run this script in python2, please refer to [this issue](https://github.com/peteanderson80/bottom-up-attention/issues/36#issuecomment-421332195) for more information.

Best,
Jianjie
