### ISSUE TITLE
how to generate long sentence

### ISSUE THREAD

**Issue by catfish132** [jianjieluo/SCD-Net#2]
I try to use this code to generate long text. However, I found that model tend to generate short sentences, I wonder why?

**Comment by jianjieluo** [comment]
Hi, @catfish132 ,

SCD-Net only learns the output text length implicitly from the training sentences. The input of SCD-Net only contains image and retrieved sentence, therefore you can not explicitly control the output sentence length. You can re-train the SCD-Net with additional input `output_length`, in this way you can control the SCD-Net output length at inference.

Best,
Jianjie
