### ISSUE TITLE
how to use the cross-modal retrieval modal in this task?

### ISSUE THREAD

**Issue by Sparkle-Q** [jianjieluo/SCD-Net#3]
I didn't find the process that search the semantically relevant sentence from training sentence pool by using an off-the-shelf cross-modal retrieval modal, which is mentioned in the paper. Could you please show me how to do this process in the code?

**Comment by jianjieluo** [comment]
Hi, @Sparkle-Q ,

Sorry for the late response. We use the CLIP cosine similarity score between the input image and the training sentence pool to retrieve the semantic prior. You can further check [this repo](https://github.com/openai/CLIP) for more reference.

Best,
Jianjie

**Comment by 1301358882** [comment]
> Sorry for the late response. We use the CLIP cosine similarity score between the input image and the training sentence pool to retrieve the semantic prior. You can further check [this repo](https://github.com/openai/CLIP) for more reference.

Hello, may I ask how the training sentence pool is obtained? Where can I find the code? Thank you very much.
