### ISSUE TITLE
Question about Generating Repeated Tokens while Inferencing

### ISSUE THREAD

**Issue by AlonzoLeeeooo** [jianjieluo/SCD-Net#6]
Hi @jianjieluo ,

Thanks for the amazing work! I am working on transferring the architecture of SCD-Net upon medical radiology reports generation. But I figure out that the trained model tends to generate repeated tokens during testing. Have you ever encountered this kind of situation before? 

The training losses and visualized results are shown as below.
<img width="320" alt="image" src="https://github.com/jianjieluo/SCD-Net/assets/68578066/6aa8019e-9cd1-44a8-ac30-f9fc0388e041">
<img width="883" alt="image" src="https://github.com/jianjieluo/SCD-Net/assets/68578066/845e6460-0b87-4d13-b227-de6440e47c12">
Note that the *grey* curve in the first figure is the training loss on a small medical dataset (only about 5,000 images). The *yellow* curve is the one that produces repeated tokens.

Could you please help me out with this? Thanks you in advance for replying from your busy schedule.

Best,

**Comment by mbrz97** [comment]
Hi @AlonzoLeeeooo,

Did you reach any promising results running this on your medical dataset? I'm also working applying this model to a medical dataset. I'd really appreciate it if you could let me know how it went.

Thanks!

**Comment by AlonzoLeeeooo** [comment]
> Hi @AlonzoLeeeooo,
> 
> Did you reach any promising results running this on your medical dataset? I'm also working applying this model to a medical dataset. I'd really appreciate it if you could let me know how it went.
> 
> Thanks!

Hi @mbrz97 ,

You can try [this repo](https://github.com/catfish132/DiffusionRRG), which is an implementation for radiology report generation (RRG).

**Comment by mbrz97** [comment]
@AlonzoLeeeooo Thank you! This is incredibly helpful.

I'm also curious to know if you were able to resolve the repeating token problem mentioned in your original post.

**Comment by AlonzoLeeeooo** [comment]
> @AlonzoLeeeooo Thank you! This is incredibly helpful.
> 
> I'm also curious to know if you were able to resolve the repeating token problem mentioned in your original post.

I've solved the token repeated problem by using [another repo](https://github.com/catfish132/DiffusionRRG), which is originated from this repo and adapted for radiology report generation on IU X-Ray and MIMIC-CXR. You can try training SCD-Net with its codebase.
